#!/usr/bin/python3
# (BFS using arrays)
grid = [
    [0,0,1,0],
    [1,0,1,0],
    [0,0,0,0],
    [0,1,1,0]
]

rows, cols = len(grid), len(grid[0])
visited = [[False]*cols for _ in range(rows)]

queue = [(0,0,0)]  # row, col, distance
visited[0][0] = True

while queue:
    r,c,d = queue.pop(0)
    if r == rows-1 and c == cols-1:
        print("Shortest path length:", d)
        break

    for dr, dc in [(1,0),(-1,0),(0,1),(0,-1)]:
        nr, nc = r+dr, c+dc
        if 0 <= nr < rows and 0 <= nc < cols:
            if not visited[nr][nc] and grid[nr][nc] == 0:
                visited[nr][nc] = True
                queue.append((nr,nc,d+1))
